modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://gitlab.com/DragonForge/HammerLib/issues"
license="All rights reserved"
[[mods]]
modId="hammerlib"
version="${file.jarVersion}"
displayName="HammerLib"
updateJSONURL="http://dccg.herokuapp.com/api/fmluc/247401"
displayURL="http://dccg.herokuapp.com/api/fmlhp/247401"
logoFile="logo.png" #optional
authors="Zeitheron" #optional
description='''
HammerLib is an essential tool for developing mods easily.
Packed with a lot of utilities, this library provides nearly anything a modder would need, in one handy package!
'''
[[dependencies.hammerlib]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.75,)"
    ordering="NONE" # NONE/BEFORE/AFTER
    side="BOTH"
[[dependencies.hammerlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.,1.19)"
    ordering="NONE"
    side="BOTH"
